### PR TITLE
Show filter counter only when one or more filters active

### PR DESCRIPTION
**Pull request by bembelimen**
Readd from Elmars commits

### CODE REVIEW

**Comment by brianteeman** [comment]
This fails accessibility. Displaying a number with no obvious meaning is worse than not displaying anything

**Comment by fancyFranci** [comment]
@brianteeman you mean there should be no number at all? Even when filters are active? Then how should we indicate that there are active filters?

**Comment by brianteeman** [comment]
I mean that just having a number on its own is meaningless

**Comment by fancyFranci** [comment]
The number is in front of the word "Filter Options". This is not enough? 
grafik
Do you have an idea how it would be more accessible?

**Comment by brianteeman** [comment]
So what does "2 filter options" mean? It could mean different things. 
1. There are 2 filter options available
2. There are 2 filter options that have been set

**Comment by chmst** [comment]
As a user I would think:
It is a red notification, so it means that there are two filter options set.
A number without special colour would indicate the number of filter options.

For a11y: The number must have a title

**Comment by brianteeman** [comment]
How do you see the colour red with a screen reader?
How do you understand the meaning of a colour if you can't see colours?

**Comment by chmst** [comment]
Right. So we need a title and a sr-only. @fancyFranci asked, how she can improve the solution, I'll try to help here.

**Comment by brianteeman** [comment]
I still would not rely on colour as a single indicator for sighted users

**Comment by brianteeman** [comment]
I still dont think that just displaying a number satisfies the requirement to indicate that the table is being filtered as you should indicate filtered by what not just filtered by something

**Comment by chmst** [comment]
I have made a RFC long time ago in V4.0 dev for this topic. https://issues.joomla.org/tracker/joomla-cms/23572. It is hard to find a solution here which meets all requirements. 

Having the filter open in a container at the right side would be great but there is not enough place

A caption is good but does not always work- (or does it? I know that you are working there @brianteeman, but do not know if it works when the filter is not related to a table column?).

A combination of caption and the notification button could be a good combination.

**Comment by bembelimen** [comment]
So would something like ```<span class="badge badge-pill badge-danger js-stools-filter-count">5 <span class="sr-only">filters are set for this list</span></span>```

Satisfy the a11y requirements?

**Comment by brianteeman** [comment]
It seems like it should but I am not in front of a pc to check that where this code is placed it will be read by a screen reader or not

**Comment by chmst** [comment]
I have tested this with screenreader and suggest : hide tht badge for screenreader with aria-hidden="true" and add the sr-only information as @bembelimen suggests.

**Comment by bembelimen** [comment]
With the new ("old") filter we don't need the number anymore.
See: https://github.com/joomla/backend-template/issues/283#issuecomment-499642260 and https://github.com/joomla/backend-template/pull/318

**Pull request closed without merging**
