### PR TITLE
Release 090518

### PR DESCRIPTION
**Pull request by coolcat-creations**
Pull Request for Issue # .

### Summary of Changes
PR for changes between yesterday and now

### CODE REVIEW

**Review by Hackwar — CHANGES_REQUESTED** [review]
Applying this PR the way it is now makes the backend template worse. The buttons are completely mangled. Before this can be merged, please clean that up and finalise this. The release branch is not allowed to be in worse shape after your changes have been merged in than before. In theory the release branch should always be in a state where you can release it right this moment to the public.

**Comment by coolcat-creations** [comment]
Unfortunately it's not possible. 
I made style changes that:

- Make all buttons that follow Boostrap Standard work
- Make all buttons and dropdowns that follow Joomlas way to implement buttons work

It will be not possible to make a style that supports broken/wrong markups of buttons and every possibilty of wrong html structure.

As discussed many times before, I am not able to fix the wrong html structure in the deep JS and PHP  of the J4 backend. This PR creates a unified style for all buttons, beside the few buttons that have wrong a markup. Many hours of work for the trash because no one knows how to fix the wrong html structure.

**Comment by brianteeman** [comment]
> I am not able to fix the wrong html structure in the deep JS and PHP of the J4 backend. This PR creates a unified style for all buttons, beside the few buttons that have wrong a markup. 

What is the wrong markup? Then we can fix it.

**Comment by coolcat-creations** [comment]
Thank you, that would be great.

The first things are in the toolbar. There are Buttons that have classes with btn-sm and some not. We need to decide for one class. It can be "btn" "btn btn-sm" or "btn btn-lg".
btn will display regular size, btn-sm will display small buttons, btn-lg will display large buttons.
A mix of these classes causes a mix of sizes in the toolbar and so this is not an error of the stylesheet but in the html.

The second thing is the Action button markup. I tried to edit it directly in the DOM and it was displayed correctly when you use the same markup like the "Save and Close" button. Currently with this PR it's completely broken.

All of the changes in the (s)css had been tested with regular Bootstrap 4 Markup and the common use in the Backend. For both: LTR and RTL.

Next one was fixing the svg offset tweak in the dropdowns that caused many errors like white Backgrounds overlaying text, and no RTL support. I fixed them in the Filter Options in the article manage overview. The scss does not work for any edit Dropdowns or for example the context dropdowns. The reason for that is that there are different html structures for the same things. 
As far as I could see there are 4 Types of Dropdowns (Choices, Multiselect, Chosen, Buttondropdowns). If each of them is used constantly they will work everywhere as expected. But like the example with Save & Close and Action Button I would rather not write SCCS for every possibility of html structures but define the standard and unify the output.
So if you look at the filter dropdowns in the Search Filters, on the top right of the article manage overview in en-GB / and persian, they work. 

Another thing is that there was a complain that there are editbuttons and cog icons in the dashboards. The difference between them two is, that the cog icons open a dropdown and the edit icons open the edit form. So they need to be two different buttons because of different context and not fault of the scss. What's true is, that i need to either add a button border to the link buttons or push the dropdown higher. TBH thats a 5 minute change.

### Screenshot of tested appereance of regular Markup (without spans inside)
grafik

### Example of different Buttonsizes due to differently used classes (btn-sm) - see also that the buttons with icon spans inside work correctly and also the dropdown toggles
grafik

### Example of the broken action button - where the same works in save and close
grafik

### Example on how filters are displayed (also Example of missing btn-danger and icon in clear button)
grafik

### Example on how the same types of fields are displayed wrong
grafik

I searched like 14 hours to change the markup and asked very often to help to find where to change. I am very sorry but I can't find it.

**Comment by brianteeman** [comment]
The issue with the toolbar buttons is coming from the difference between the button being loaded directly and the button being loaded by the custom element joomla-toolbar-button

Make them all use the custom element as they should be and you solve the issue (you can remove the btn-sm at the same time or make them all use btn-sm

searchtools clear is missing an icon because there isnt one in the markup `layouts\joomla\searchtools\default\bar.php`

The styling issues on the dropdown filters is because they are not getting to use the roboto font

I dont see any issue with the actions button - can you point me to where you are seeing that

**Comment by brianteeman** [comment]
i strongly suspect that one of the reasons you are having difficulties is that some of the markup is coming from the javascript of the custom elements not the php

**Comment by coolcat-creations** [comment]
We see clearly two different versions of the stylesheet, When all the commits were taken away from the release branch probably I could not rescue it anymore. I dont know :-( 
Here is the broken Action Button:
grafik
Yes I know, the markups are completly mixed, one is with a custom element, one not, one contains a custom element one is surrounded by it. If everything would be done the same way it would help to fix the remaining issues (very) fast. But my second issue now is somehow that not all my changes seem to be in this repo anymore, when we compare my screens to yours. :-(

**Comment by brianteeman** [comment]
making the markup consistent should NOT be a template issue. too much non-template changes are happening here. if you have a problem with the markup then open an issue on the main repo. none of it is hard to fix and there are lots of people who can help but saying you have explained things many times before and that no one knows how to fix it is not helpful to anyone especially when only a few people are even aware you have found a problem. As no one knows what is happening here people cant help you. especially when you have moved so far from your design poposal

**Comment by coolcat-creations** [comment]
Yes it's true that I moved a bit from the initial concept, but thats also because I gathered a lot of feedback from the community and other teams trying to make things better. Other things were not moved by me but just not done like they were supposed to be done, can't force anyone to follow something strictly. It's still Open Source ;-)

And I hope it's going for everyone into the right direction. I was fixing the css for the buttons for the merge but we can't merge without the css and we can't add the css without the fixes of the html structure. So I am quite helpless what to do now? Posting a issue in the main repo? Or just waiting for the merge and trying to fix the buttons afterwards again ? Then the unified css will break the buttons again because of the wrong structure so the PR can't be merged. 

Would have been easier for me if it would not be reverted backwards but given a try to fix this custom elements stuff. Then everyone would see also where things have to be fixed.

To bring it to a point: I dont' know how to solve this situation now.

**Comment by brianteeman** [comment]
This situation was highly predictable when you enforced your closed development policy. Now you are suffering as a result. **This repo should only be touching the template.** Anything other than that should be done in the normal way on the main repo. As it is now its going to be a nightmare to test this work as it touches (and breaks) so many non-template things.

**Comment by coolcat-creations** [comment]
I did not enforce anything. Stop accusing me. I just wondered about your productive way of communication and was happy that you realized that talking on a normal level is better. But seems you are going back to your usual behaviour. Sad thing.

**Comment by brianteeman** [comment]
Keep it up - you did enforce the closed development and now it bites you in the but and shows why open development is more productive. This is not about personalities but about the future of joomla. You've been given the keys to craft the entire ui - stop blaming others or saying that no one knows how to fix it. You just didnt ask the right people in the right place.  I already created an issue for the toolbar icons #24850 - easy to fix

**Comment by coolcat-creations** [comment]
Stop writing things that are not right. I have absolutely no possibility to enforce anything in Joomla. The decision makers are other people. This is open source - anyone can help and do something. Just because a few people asked for a place to prepare a PR it does not mean that I enforced anything. Or do you give everyone access to your computer to see what you might submit maybe one day?

**Comment by brianteeman** [comment]
Keep up with the accusations and you will have killed another attempt at a new admin template. i prefer to be constructive and fix issues

**Pull request closed without merging**
