### PR TITLE
Make quicicons more compact

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Make quickicons more compact. This is an alternative to the original design with two separate buttons.
I removed the text from additional button. The Text remains as beefore for screenreaders and is added as titile to the link. 

quickicons-compact

@brianteeman could you please have a look here to make sure that it does not affect a11y.

### CODE REVIEW

**Comment by brianteeman** [comment]
From a design perspective it is better

As I said before there is an a11y issue with the code (same problem with the menu) - still trying to get a proper fix for that but it should not hold up merging this

**Comment by simbus82** [comment]
Nice! Better than before!
But i think you have to move the "counter" out of the space between the icon and his label. It's really wrong for an UI "breaking" the proximity between icon and his label.

image
This type of counters, in common use and in the UI that the user expects, are like notifications and must be positioned in a more recognizable way

Furthermore, a number that appears there without a different style seems like an error, not an information

Example:
image

**Comment by bembelimen** [comment]
I think if we move the number, the context is missing:
1 user
0 articles
3 modules

**Comment by C-Lodder** [comment]
Or just remove the counter completely?

**Comment by chmst** [comment]
Now on dev 4.0 https://github.com/joomla/joomla-cms/pull/25865

**Pull request closed without merging**
