### PR TITLE
Quickicon improvements

### PR DESCRIPTION
**Pull request by bembelimen**
Use context for different plugin loading.

### CODE REVIEW

**Comment by brianteeman** [comment]
I assume this is to allow 3pd quickicons to display? Will test tomorrow

**Comment by brianteeman** [comment]
I am guessing this is the intended display?

image

If so then I guess that works from a display perspective although I am not a fan of the title.

**The problem comes with the Edit module screen for the module.**

The logic is very confusing here for the user. Icons can be selected based on their group and in some cases additionally by the toggle.

image

**Comment by bembelimen** [comment]
This PR resolves the "bad concept style" of the current implementation with the plugin implementation.

The big padding is removed via: https://github.com/joomla/backend-template/pull/280
The "problem" of the quickicons at all is the combination of "hard coded" icons directly from the module itself and the plugin triggers which allows plugins to laod their own icons. So the "group" is responsible for the context of the plugin trigger, the toggles for the hard coded icons.

The best solution would probably be: create a plugin for each icon. But that's out of scope for this PR.

This PR should just smoothing out code smells.

**Review by chmst — APPROVED** [review]

**Comment by chmst** [comment]
The code works fine for me.  If it is merged, we can work on a better solution. I agree that this is confusing for users and also has to be improved concerning  a11y.

**Pull request merged**
