### PR TITLE
Remove unused files from the tmpl

### PR DESCRIPTION
**Pull request by brianteeman**
Done in this repo to make it easier so you dont edit files that we dont use and to avoid merge conflicts

If you prefer i can submit it to the main repo instead

### CODE REVIEW

**Comment by bembelimen** [comment]
I'm ok with making it here. But probably you have to edit this "file deletion script" in com_admin, too?

**Comment by brianteeman** [comment]
my understanding is that, that file is being updated by @wilsonge and not in each pr

**Comment by Hackwar** [comment]
No, that script is generated later automatically.

**Comment by bembelimen** [comment]
Ok, thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
