### PR TITLE
adjust menu and url links

### PR DESCRIPTION
**Pull request by lavipr**
Pull Request for Issue # .

### Summary of Changes
some links were not correct. E.g. after edit the url changes with view parameter and the links in the menu don't match anymore so the correct active menu element can't be set to active.
So most of the links are now the same before and after edit.

### Testing Instructions
Please install new and check the active menu items.

### Expected result
When switching from a list view to the edit view and coming back to the list view, the menu should have an active open menu like before entering to the edit view.

### Actual result
After editing there is no active menu-item.

### CODE REVIEW

**Comment by lavipr** [comment]
This works when menu items have no submenu (so the third menu right to the menu).
And I don't know how to set the right url for com_fields&view=groups. There need to be add a context but I can't find the right file to change it.

**Review by bembelimen — APPROVED** [review]

**Review by Hackwar — APPROVED** [review]

**Comment by brianteeman** [comment]
Surely this is nothing to do with the template and should be handled in the  main repo. There you will see another pr https://github.com/joomla/joomla-cms/pull/24801 that addresses this issue - the correct way

**Comment by lavipr** [comment]
Thanks.

**Comment by lavipr** [comment]
Thanks. This can be closed now, as there is a pr in the main repo.

**Comment by brianteeman** [comment]
This is a great example why the practice of some people making direct commits to this repo without it being subject to peer review has caused you so many problems in this repo.

**Pull request closed without merging**
