### PR TITLE
refactor modules used in the status position

### PR DESCRIPTION
**Pull request by brianteeman**
General cleanup, remove unused code etc

Pull Request for Issue #333 

Note the count of unread messages is not working. I don't know why BUT it was broken before this so is beyond the scope here

### CODE REVIEW

**Comment by brianteeman** [comment]
I think there may be some further improvements required for a11y but I dont see them

**Comment by bembelimen** [comment]
Hello @brianteeman could you please also update the update files: https://github.com/joomla/backend-template/blob/release/administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-05-07.sql and https://github.com/joomla/backend-template/blob/release/administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-05-07.sql
Thx.

**Comment by brianteeman** [comment]
Do you want me to edit those or create new ones. iirc a current install will not see those older updates. Which is where it gets complicated if its a new update file because you have an update query and an insert query. Or do I need more coffee?

**Comment by bembelimen** [comment]
As we don't have to be B/C you can just edit the existing one. They are from "us", so they're not in the core yet.

You just have to rename the module names like here: https://github.com/joomla/backend-template/pull/360/files#diff-35a1b24301ed7c8dc812bdce111ab988

**Comment by brianteeman** [comment]
done as requested

**Review by bembelimen — APPROVED** [review]

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
