### PR TITLE
Quickicon cleanup

### PR DESCRIPTION
**Pull request by Hackwar**
I was contacted by @angieradtke with some code for the quickicons. I kinda like this cleaner look and thus wanted to bring this up here for debate.

### CODE REVIEW

**Comment by brianteeman** [comment]
To save time can you post a screenshot please

**Comment by chmst** [comment]
quickicons new

**Comment by brianteeman** [comment]
Thanks @chmst 

I am not a designer so wont comment if it looks better with rounded corners and a shadow or flat and square

But from a visual usability perspective having the count and the stats as one box is now more confusing and even harder to scan and realise there are two buttons

**Comment by chmst** [comment]
The scss does not use variables. So please don't merge. 

I like the light and elegant look of the buttons.

I agree with @brianteeman 
> But from a visual usability perspective having the count and the stats as one box is now more confusing and even harder to scan and realise there are two buttons

On my smartphone the separated buttons are better

**Comment by chmst** [comment]
Further Reflection: The colours we use now on quickicons are either link colours, calculated from template colour settings or success/warning colours. Changes must be consistent in the colour concept.

**Comment by angieradtke** [comment]
Hi ,

this was only a suggestion.
contrast of light blue quickicons  is not enough for AAA.

 Brian: The first look at the dashboard is for orientation. Therefore it is important from my point of view to group the things that belong together to get a quick overview.  The targeted addition of individual actions is the  second step in the visual perception.

Angie

**Comment by brianteeman** [comment]
I agree about the grouping
I just dont agree that the "targeted addition of individual actions" works visually
and of course it doesnt work for screen readers at all currently

**Comment by chmst** [comment]
> contrast of light blue quickicons is not enough for AAA. 

We do not target AAA but AA

**Comment by bembelimen** [comment]
> But from a visual usability perspective having the count and the stats as one box is now more confusing and even harder to scan and realise there are two buttons

So should we have something like:
grafik

**Comment by angieradtke** [comment]
this is a good compromis .-)

**Comment by chmst** [comment]
@bembelimen yes,this  looks good for me. 
There is still the question of colours. The colours variables at the moment are link coulours, But we could try the colour of promary buttons instead.

**Comment by angieradtke** [comment]
Now you got:  atum-link-color:                 #2077dd
link-color

**Comment by bembelimen** [comment]
Updated PR with correct usage of variables etc.: https://github.com/joomla/backend-template/pull/368

**Pull request closed without merging**
