### PR TITLE
Set pagination to the right and style

### PR DESCRIPTION
**Pull request by HRIT-Florian**
Pull Request for Issue # .

### Summary of Changes

Set pagination to the right and style 

### Testing Instructions

Test pagination  style

### Expected result

Pagination should now be right and the hover and active link color should be tum-text-light and atum-bg-dark

### Actual result

Pagination is left aligned

### Documentation Changes Required

No

### CODE REVIEW

**Comment by brianteeman** [comment]
What happens with an RTL language

**Comment by HRIT-Florian** [comment]
@brianteeman should be fine 👌

grafik

**Comment by brianteeman** [comment]
Sorry this doesnt work

image

The active page is white on white and white on grey for hover

**Comment by HRIT-Florian** [comment]
@brianteeman at which view did you get the style bug?
Did checked some views and can't reproduce it.
npm  you've been running I suppose?
npm run build:css

**Comment by brianteeman** [comment]
must have been css browser cached as it works now. - sorry

**Review by bembelimen — APPROVED** [review]

**Pull request merged**
