### PR TITLE
Fixing dropdown toolbar buttons

### LINKED ISSUE #193: joomla-toolbar-button
image

If you look at the image you can see that there is a blank line with a grey vertical line before each button.

This is coming from 
```
joomla-toolbar-button {
    border: 1px solid var(--border);
}
```

If that css is removed then you get the following which I am sure is the intended view?
image

You can also see an issue with the "Batch" text being aligned differently to the other buttons. This is because the icon for the other buttons have a width of 26px coming from
```
.btn-group .dropdown-menu [class*=" icon-"], .btn-group .dropdown-menu [class^=icon-] {
    width: 26px;
}
```
As the batch is using `class="fa fa-square"` the css above is not being applied

### PR DESCRIPTION
**Pull request by Hackwar**
This fixes #193. There are 2 issues:

- There are ugly boxes above the entries in a dropdown toolbar button. This removes those.
- The batch button has a wrong icon and that is also fixed.

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry but this is not the correct fix for the icon. @wilsonge has already said that we should be moving to use fa icons so there needs to be a different solution to this

**Comment by brianteeman** [comment]
You should do what has been done elsewhere and add support for fa icons - something like this in the _dropdown.scss should work
```

.btn-group .dropdown-menu {
  box-shadow: $atum-box-shadow;

  [class^='icon-'],
  [class*=' icon-'],
  [class*='fa'],
  [class*='fa']{
    margin-right: .25rem;
  }
}
```

**Comment by Hackwar** [comment]
Should be better now.

**Comment by brianteeman** [comment]
My mistake in the suggestion but lines 10 and 11 are identical one of them should be  with a ^ and space

**Review by nadjak77 — APPROVED** [review]

**Pull request merged**
