### PR TITLE
Remove css files from the html directory

### PR DESCRIPTION
**Pull request by chmst**
As title says

### CODE REVIEW

**Review by bembelimen — APPROVED** [review]

**Comment by brianteeman** [comment]
This might have been in the wrong folder but are you sure it could simply be deleted. Doesnt tinymce use this

**Comment by chmst** [comment]
I could not find a usage or a documentation. If these css definitions are used by the tiny we must add them into the media folder.

**Comment by brianteeman** [comment]
PLG_TINY_FIELD_CSS_DESC="By default the Plugin looks for an editor.css file. If it can't find one in the default template CSS folder, it loads the editor.css file from the system template."

**Comment by brianteeman** [comment]
found the bug. the css should have been in the SITE template

**Pull request merged**
