### PR TITLE
Use generic scss for com_installer and com_joomaupdate

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Removed scss files for com_installer and com_joomlaupdate to keep the number of scss files small.
Add class "options-fieldset" to fieldsets

### Testing Instructions
For com_joomlaupdate testing requires the simulation of different special use cases, where the different layouts are displayed.

### CODE REVIEW

**Comment by brianteeman** [comment]
**If** the only reason was to keep the number of scss files low it's not a good idea as there is no real benefit

**Comment by chmst** [comment]
The main reason is that one single class is better to maintain, it avoids different views when the layout of the blocks in option views is changed. 
Less files in scss folder is a nice side effect.
 
BTW: These layouts seem to be old, they still use Layout tables. But this is not in scope here

**Comment by brianteeman** [comment]
Did you test this? The PR removes a class "uploadform". This is used as an identifier in the javascript

**Comment by chmst** [comment]
Thank you!

**Review by Hackwar — APPROVED** [review]

**Pull request merged**
