### PR TITLE
fix change id to class of cpanel-modules

### PR DESCRIPTION
**Pull request by lavipr**
Pull Request for Issue # .

### Summary of Changes
Since the id="cpanel-modules" are changed to class="cpanel-modules" it wasn't anymore possible to unpublish modules, so the js was changed to search for classes with the name instead of the id.

### Testing Instructions
try to unpublish modules on the cpanel.

### Expected result
the module gets unpublished

### Actual result
nothing happens.

### CODE REVIEW

**Review by chmst — APPROVED** [review]
Thank you!

**Comment by brianteeman** [comment]
Why not put the id back. It should have one

**Comment by bembelimen** [comment]
See: https://github.com/joomla/backend-template/pull/223

**Comment by chmst** [comment]
After re-thinking I have added the id to the layout file. So there's no need to change the existing js  file. But thank you @lavipr for finding the bug!

**Comment by lavipr** [comment]
Closed as the id was readded to the layout file  #223

**Pull request closed without merging**
