### PR TITLE
Adapt layout of com_installer with fieldset and legend

### PR DESCRIPTION
**Pull request by chmst**
Adapt the layout of installer layouts.. 
installer-screen

### CODE REVIEW

**Comment by brianteeman** [comment]
Am I missing something here but there is only css - no markup

**Comment by chmst** [comment]
That is all right, only a little bit css was necessary for layouts "install from folder, from package file, from url".

**Comment by brianteeman** [comment]
1. Sorry I assumed the legend etc was defined in the xml. I see now its hardcoded in the plugin
2. There is an HR in the code below the legend but I dont see that in your screenshot

That's why I thought something was missing

**Comment by bembelimen** [comment]
Did you try just giving the specific classes: https://github.com/joomla/backend-template/blob/release/administrator/templates/atum/scss/blocks/_layout.scss#L34

**Comment by Hackwar** [comment]
With #403 is this still necessary?

**Comment by chmst** [comment]
Closed for #403

**Pull request closed without merging**
