### PR TITLE
Reorganise menu language file

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #228 .

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks good to me. Someone will probably complain that  apple_pear should come before apples_pears in the sort order and it doesnt address the item in #255

**Comment by chmst** [comment]
@brianteeman I'll do a recherche about alpharodering :) It was the plugin in my IDE.

**Comment by brianteeman** [comment]
I agree with the sort but someone else doesnt and will object

**Comment by bembelimen** [comment]
Could you please fix #255 here, too? Thanks.

**Review by bembelimen — APPROVED** [review]

**Pull request merged**
